### ISSUE TITLE
Test failure on main

### ISSUE THREAD

**Issue by goerch** [JuliaDebug/JuliaInterpreter.jl#501] opened 2021-12-07 12:12 UTC
I just forked `JuliaInterpreter` and running `versioninfo(); include("test/runtests.jl")` yields

```
Julia Version 1.8.0-DEV.1104
Commit 2cfd57d0b1 (2021-12-06 17:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\Win10\AppData\Local\atom\app-1.58.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6
Test Failed at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\runtests.jl:4
  Expression: isempty(detect_ambiguities(JuliaInterpreter, Base, Core))
   Evaluated: isempty(Tuple{Method, Method}[(get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(t::AbstractDict, key, default) in Base at abstractdict.jl:543), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(d::IdDict{K, V}, key, default) where {K, V} in Base at iddict.jl:155), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(wkh::WeakKeyDict{K}, key, default) where K in Base at weakkeydict.jl:110)])
ERROR: LoadError: There was an error during testing
in expression starting at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\runtests.jl:4
```

**Comment by aviatesk** [comment] 2021-12-07 12:20
This isn't reproduced at least on our CI. What's your activated environment?

**Comment by goerch** [comment] 2021-12-07 12:23
> This isn't reproduced at least on our CI. What's your activated environment?

Yes, I noticed. `Pkg.status()` is

```
Pkg.status()
Project JuliaInterpreter v0.8.21
Status `C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\Project.toml`
  [da1fd8a2] CodeTracking v1.0.6
  [b77e0a4c] InteractiveUtils
  [9a3f8284] Random
  [cf7118a7] UUIDs
```

**Comment by aviatesk** [comment] 2021-12-07 12:28
I guess `Pkg.test()` won't yield the error?

**Comment by KristofferC** [comment] 2021-12-07 12:35
The references to `CommonMark` probably means you have that loaded in the session and it is interfering with the ambiguity test.

**Comment by goerch** [comment] 2021-12-07 12:36
Reducing to `versioninfo(); Pkg.status(); @test isempty(detect_ambiguities(Base, Core))` yields

```
Julia Version 1.8.0-DEV.1104
Commit 2cfd57d0b1 (2021-12-06 17:59 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\Win10\AppData\Local\atom\app-1.58.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6
Status `C:\Users\Win10\.julia\environments\v1.8\Project.toml`
  [c52e3926] Atom v0.12.35
  [6e4b80f9] BenchmarkTools v1.2.0
  [c3a54625] JET v0.5.2 `..\..\..\Documents\GitHub\JET.jl`
  [e5e0dc1b] Juno v0.8.4
  [1914dd2f] MacroTools v0.5.9
Test Failed at none:1
  Expression: isempty(detect_ambiguities(Base, Core))
   Evaluated: isempty(Tuple{Method, Method}[(get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(wkh::WeakKeyDict{K}, key, default) where K in Base at weakkeydict.jl:110), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(d::IdDict{K, V}, key, default) where {K, V} in Base at iddict.jl:155), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(t::AbstractDict, key, default) in Base at abstractdict.jl:543)])
ERROR: There was an error during testing
```

**Comment by goerch** [comment] 2021-12-07 12:38
`Pkg.test()` yields

```
     Testing JuliaInterpreter
      Status `C:\Users\Win10\AppData\Local\Temp\jl_2ennRM\Project.toml`
  [da1fd8a2] CodeTracking v1.0.6
  [a93c6f00] DataFrames v0.21.8
  [cd3eb016] HTTP v0.9.17
  [aa1ae85d] JuliaInterpreter v0.8.21 `C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl`
  [438e738f] PyCall v1.92.5
  [70df011a] TableReader v0.4.0
  [48a634ad] Tensors v1.9.1
  [ade2ca70] Dates `@stdlib/Dates`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [a63ad114] Mmap `@stdlib/Mmap`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
      Status `C:\Users\Win10\AppData\Local\Temp\jl_2ennRM\Manifest.toml`
  [fa961155] CEnum v0.4.1
  [324d7699] CategoricalArrays v0.8.3
  [d360d2e6] ChainRulesCore v1.11.2
  [9e997f8a] ChangesOfVariables v0.1.1
  [da1fd8a2] CodeTracking v1.0.6
  [ba30903b] CodecXz v0.7.0
  [944b1d66] CodecZlib v0.7.0
  [6b39b394] CodecZstd v0.7.2
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.40.0
  [8f4d0f93] Conda v1.6.0
  [9a962f9c] DataAPI v1.9.0
  [a93c6f00] DataFrames v0.21.8
  [864edb3b] DataStructures v0.18.10
  [e2d170a0] DataValueInterfaces v1.0.0
  [163ba53b] DiffResults v1.0.3
  [b552c78f] DiffRules v1.5.0
  [ffbed154] DocStringExtensions v0.8.6
  [f6369f11] ForwardDiff v0.10.23
  [cd3eb016] HTTP v0.9.17
  [83e8ac13] IniFile v0.5.0
  [3587e190] InverseFunctions v0.1.2
  [41ab1584] InvertedIndices v1.1.0
  [92d709cd] IrrationalConstants v0.1.1
  [82899510] IteratorInterfaceExtensions v1.0.0
  [692b3bcd] JLLWrappers v1.3.0
  [682c06a0] JSON v0.21.2
  [aa1ae85d] JuliaInterpreter v0.8.21 `C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl`
  [2ab3a3ac] LogExpFunctions v0.3.5
  [1914dd2f] MacroTools v0.5.9
  [739be429] MbedTLS v1.0.3
  [e1d29d7a] Missings v0.4.5
  [77ba4419] NaNMath v0.3.5
  [bac558e1] OrderedCollections v1.4.1
  [69de0a69] Parsers v2.1.2
  [2dfb63ee] PooledArrays v0.5.3
  [21216c6a] Preferences v1.2.2
  [438e738f] PyCall v1.92.5
  [189a3867] Reexport v0.2.0
  [fdea26ae] SIMD v3.3.1
  [a2af1166] SortingAlgorithms v0.3.1
  [276daf66] SpecialFunctions v1.8.1
  [90137ffa] StaticArrays v1.2.13
  [856f2bd8] StructTypes v1.8.1
  [70df011a] TableReader v0.4.0
  [3783bdb8] TableTraits v1.0.1
  [bd369af6] Tables v1.6.0
  [48a634ad] Tensors v1.9.1
  [3bb67fe8] TranscodingStreams v0.9.6
  [5c2747f8] URIs v1.3.0
  [81def892] VersionParsing v1.2.1
  [efe28fd5] OpenSpecFun_jll v0.5.5+0
  [ffd25f8a] XZ_jll v5.2.5+2
  [3161d3a3] Zstd_jll v1.5.0+0
  [0dad84c5] ArgTools v1.1.1 `@stdlib/ArgTools`
  [56f22d72] Artifacts `@stdlib/Artifacts`
  [2a0f44e3] Base64 `@stdlib/Base64`
  [ade2ca70] Dates `@stdlib/Dates`
  [8bb1440f] DelimitedFiles `@stdlib/DelimitedFiles`
  [8ba89e20] Distributed `@stdlib/Distributed`
  [f43a241f] Downloads v1.5.1 `@stdlib/Downloads`
  [7b1f6079] FileWatching `@stdlib/FileWatching`
  [9fa8497b] Future `@stdlib/Future`
  [b77e0a4c] InteractiveUtils `@stdlib/InteractiveUtils`
  [b27032c2] LibCURL v0.6.3 `@stdlib/LibCURL`
  [76f85450] LibGit2 `@stdlib/LibGit2`
  [8f399da3] Libdl `@stdlib/Libdl`
  [37e2e46d] LinearAlgebra `@stdlib/LinearAlgebra`
  [56ddb016] Logging `@stdlib/Logging`
  [d6f4376e] Markdown `@stdlib/Markdown`
  [a63ad114] Mmap `@stdlib/Mmap`
  [ca575930] NetworkOptions v1.2.0 `@stdlib/NetworkOptions`
  [44cfe95a] Pkg v1.8.0 `@stdlib/Pkg`
  [de0858da] Printf `@stdlib/Printf`
  [3fa0cd96] REPL `@stdlib/REPL`
  [9a3f8284] Random `@stdlib/Random`
  [ea8e919c] SHA v0.7.0 `@stdlib/SHA`
  [9e88b42a] Serialization `@stdlib/Serialization`
  [1a1011a3] SharedArrays `@stdlib/SharedArrays`
  [6462fe0b] Sockets `@stdlib/Sockets`
  [2f01184e] SparseArrays `@stdlib/SparseArrays`
  [10745b16] Statistics `@stdlib/Statistics`
  [fa267f1f] TOML v1.0.0 `@stdlib/TOML`
  [a4e569a6] Tar v1.10.0 `@stdlib/Tar`
  [8dfed614] Test `@stdlib/Test`
  [cf7118a7] UUIDs `@stdlib/UUIDs`
  [4ec0a83e] Unicode `@stdlib/Unicode`
  [e66e0078] CompilerSupportLibraries_jll v0.5.0+0 `@stdlib/CompilerSupportLibraries_jll`
  [deac9b47] LibCURL_jll v7.73.0+4 `@stdlib/LibCURL_jll`
  [29816b5a] LibSSH2_jll v1.9.1+2 `@stdlib/LibSSH2_jll`
  [c8ffd9c3] MbedTLS_jll v2.24.0+2 `@stdlib/MbedTLS_jll`
  [14a3606d] MozillaCACerts_jll v2020.7.22 `@stdlib/MozillaCACerts_jll`
  [4536629a] OpenBLAS_jll v0.3.17+2 `@stdlib/OpenBLAS_jll`
  [05823500] OpenLibm_jll v0.7.5+0 `@stdlib/OpenLibm_jll`
  [83775a58] Zlib_jll v1.2.12+1 `@stdlib/Zlib_jll`
  [8e850b90] libblastrampoline_jll v3.1.0+0 `@stdlib/libblastrampoline_jll`
  [8e850ede] nghttp2_jll v1.41.0+1 `@stdlib/nghttp2_jll`
  [3f19e933] p7zip_jll v16.2.1+1 `@stdlib/p7zip_jll`
Precompiling project...
  ✗ TableReader
  0 dependencies successfully precompiled in 4 seconds. 60 already precompiled.
  1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
     Testing Running tests...
Skipping Base.active_repl
Skipping Base.active_repl_backend
Skipping Base.active_repl
Skipping Base.active_repl_backend
┌ Warning: `@_inline_meta` is deprecated, use `@inline` instead.
│   caller = get_staged(mi::Core.MethodInstance) at utilities.jl:111
└ @ Core.Compiler .\compiler\utilities.jl:111
[ Info: logging macros
WARNING: Method definition foobar() in module Main at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\interpret.jl:791 overwritten at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\interpret.jl:792.
WARNING: Method definition inner(Any) in module Main at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\breakpoints.jl:97 overwritten at C:\Users\Win10\Documents\GitHub\JuliaInterpreter.jl\test\breakpoints.jl:154.
Test Summary: | Pass  Broken  Total   Time
Main tests    |  712       2    714  36.5s
     Testing JuliaInterpreter tests passed 
```

**Comment by goerch** [comment] 2021-12-07 12:39
> The reference to `CommonMark` probably means you have that loaded in the session and it is interfering with the ambiguity test.

Not intentionally, but working in Juno/Atom might be the problem?

**Comment by pfitzseb** [comment] 2021-12-07 12:40
Yup. Ambiguity tests in particular are sensitive to your whole Julia session.

**Comment by goerch** [comment] 2021-12-07 12:43
Even more reduction `versioninfo(); Pkg.status(); @test isempty(detect_ambiguities(Base, Core))`

```
Julia Version 1.8.0-DEV.1104
Commit 2cfd57d0b1 (2021-12-06 17:59 UTC)        
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64    
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\Win10\AppData\Local\atom\app-1.58.0\atom.exe"  -a
  JULIA_NUM_THREADS = 6
Status `C:\Users\Win10\.julia\environments\v1.8\Project.toml`
  [c52e3926] Atom v0.12.35
  [e5e0dc1b] Juno v0.8.4
Test Failed at none:1
  Expression: isempty(detect_ambiguities(Base, Core))
   Evaluated: isempty(Tuple{Method, Method}[(get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(wkh::WeakKeyDict{K}, key, default) where K in Base at weakkeydict.jl:110), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(t::AbstractDict, key, default) in Base at abstractdict.jl:543), (get!(f, w::CommonMark.Writer, k::Symbol) in CommonMark at C:\Users\Win10\.julia\packages\CommonMark\Cmk5S\src\writers.jl:73, get!(d::IdDict{K, V}, key, default) where {K, V} in Base at iddict.jl:155)])
ERROR: There was an error during testing
```

OK, so no more Juno/Atom. Does VS Code have the same problem?

**Comment by KristofferC** [comment] 2021-12-07 12:52
Closing since not an issue with this package. Seems like https://github.com/MichaelHatherly/CommonMark.jl/blob/e4500dba25accde85113f8a8a49d87a83b9e7584/src/writers.jl#L73 needs to specify a narrower type for `f`.

**Closed by KristofferC** 2021-12-07 12:52 UTC
