### ISSUE TITLE
`JuliaInterpreter` fails to build on Julia `1.11-alpha-2`

### ISSUE THREAD

**Issue by BenjaminRemez** [JuliaDebug/JuliaInterpreter.jl#626] opened 2024-03-28 20:07 UTC
Attempting to install Julia v.11-alpha-2 via `juliaup`, upon first firing it up, the `include Revise` command in my startup file caused the following error:

```julia
(@v1.11) pkg> build JuliaInterpreter
Precompiling project...
lld: error: undefined symbol: jl_f_memorymodifyset   ]  0/3
>>> referenced by C:\Users\breme\.julia\packages\JuliaInterpreter\vszNQ\src\builtins.jl:189
>>>               jl_CAFB.tmp(text#0.o):(julia_maybe_evaluate_builtin_3521)

lld: error: undefined symbol: jl_f_memoryreplaceset
>>> referenced by C:\Users\breme\.julia\packages\JuliaInterpreter\vszNQ\src\builtins.jl:201
>>>               jl_CAFB.tmp(text#0.o):(julia_maybe_evaluate_builtin_3521)

lld: error: undefined symbol: jl_f_memoryswapset
>>> referenced by C:\Users\breme\.julia\packages\JuliaInterpreter\vszNQ\src\builtins.jl:219
>>>               jl_CAFB.tmp(text#0.o):(julia_maybe_evaluate_builtin_3521)
  ◒ JuliaInterpreter
```

Version info:
```julia
julia> versioninfo()
Julia Version 1.11.0-alpha2
Commit 9dfd28ab75 (2024-03-18 20:35 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, icelake-client)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
```

**Comment by aviatesk** [comment] 2024-03-29 01:46
A duplicate of #621. See #621 and https://github.com/JuliaLang/julia/pull/53888.

**Closed by aviatesk** 2024-03-29 01:46 UTC
