### ISSUE TITLE
v1.12: JuliaInterpreter optimization seems to badly interact with new compressed linetable format

### ISSUE THREAD

**Issue by aviatesk** [JuliaDebug/JuliaInterpreter.jl#622] opened 2024-03-26 04:44 UTC
It looks like this "optimization" introduces a very bad interaction with the new lineinfo format: https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/28dd37ce0f7bcb357bfb820b1d6b53b98aa3796c/src/optimize.jl#L76-L92
```julia
julia> using JuliaInterpreter

julia> fnone1() = nothing;

julia> let m = only(methods(fnone1))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[2]"), nothing, svec(), "\x01\0\0\0\0\0\0\0\0\0\0\0\x01\x01\0")

julia> fnone2() = nothing;

julia> let m = only(methods(fnone2))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[4]"), nothing, svec(), "")
```

_Originally posted by @aviatesk in https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/606#issuecomment-2012195722_

**Comment by simeonschaub** [comment] 2024-09-02 19:54
I can still reproduce it with the following code by including `test/interpret.jl` first:

```julia-repl
$ julia +nightly --startup=no --project --code-coverage=user
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.12.0-DEV.1139 (2024-09-02)
 _/ |\__'_|_|_|\__'_|  |  Commit 39f2ad1e941 (0 days old master)
|__/                   |

julia> using JuliaInterpreter

julia> fnone1() = nothing;

julia> let m = only(methods(fnone1))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[2]"), nothing, svec(), "\x01\0\0\0\0\0\0\0\0\0\0\0\x01\x01\0")

julia> using TestEnv

julia> TestEnv.activate()
"/tmp/jl_kA0xSy/Project.toml"

julia> include("test/interpret.jl")
Test Summary: | Pass  Total  Time
Some tests    |    1      1  0.2s
Test Summary: | Pass  Total  Time
locals        |   15     15  1.4s
Test Summary:         | Pass  Total  Time
getfield replacements |    4      4  0.0s
Test Summary:   | Pass  Total  Time
vararg handling |    2      2  0.7s
ERROR: LoadError: MethodError: no method matching iterate(::Nothing)
The function `iterate` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  iterate(::Base.AsyncGenerator, ::Base.AsyncGeneratorState)
   @ Base asyncmap.jl:364
  iterate(::Base.AsyncGenerator)
   @ Base asyncmap.jl:364
  iterate(::LibGit2.GitRebase)
   @ LibGit2 ~/.julia/juliaup/julia-nightly/share/julia/stdlib/v1.12/LibGit2/src/rebase.jl:48
  ...

Stacktrace:
 [1] indexed_iterate(I::Nothing, i::Int64)
   @ Base ./tuple.jl:163
 [2] top-level scope
   @ ~/.julia/dev/JuliaInterpreter/test/interpret.jl:466
 [3] include(fname::String)
   @ Main ./sysimg.jl:38
 [4] top-level scope
   @ REPL[6]:1
in expression starting at /home/simeon/.julia/dev/JuliaInterpreter/test/interpret.jl:466

julia> fnone2() = nothing;

julia> let m = only(methods(fnone2))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[7]"), nothing, svec(), "")
```

Note the `--code-coverage=user`, it doesn't reproduce for me without that. This seems like an upstream bug to me?

**Comment by simeonschaub** [comment] 2024-09-04 18:11
A better reproducer:

```julia-repl
julia> using JuliaInterpreter

julia> fnone1() = nothing;

julia> let m = only(methods(fnone1))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[2]"), nothing, svec(), "\x01\0\0\0\0\0\0\0\0\0\0\0\x01\x01\0")

julia> @interpret (() -> nothing)()

julia> fnone2() = nothing;

julia> let m = only(methods(fnone2))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=true).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[5]"), nothing, svec(), "")
```

Note that if the `nothing` `@interpret (() -> nothing)()` is replaced with anything else (e.g. `@interpret (() -> 7)()`) this behavior disappears.

**Comment by simeonschaub** [comment] 2024-09-04 18:28
It also doesn't seem to have anything to do with those particular optimizations since it still happens with `optimize=false`:

```julia-repl
julia> using JuliaInterpreter

julia> fnone1() = nothing;

julia> let m = only(methods(fnone1))
           global fc = JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=false)
           fc.src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[2]"), nothing, svec(), "\x01\0\0\0\0\0\0\0\0\0\0\0\x01\x01\0")

julia> let fr = JuliaInterpreter.prepare_frame(fc, [], Core.svec())
           JuliaInterpreter.finish_and_return!(fr)
       end

julia> fnone2() = nothing;

julia> let m = only(methods(fnone2))
           JuliaInterpreter.FrameCode(m, JuliaInterpreter.get_source(m); optimize=false).src.debuginfo
       end
Core.DebugInfo(Symbol("REPL[5]"), nothing, svec(), "")
```

**Comment by simeonschaub** [comment] 2024-09-04 18:56
Reported upstream as https://github.com/JuliaLang/julia/issues/55688 with a non-JuliaInterpreter reproducer. Seems like we can close this issue here

**Closed by simeonschaub** 2024-09-04 18:56 UTC
