### ISSUE TITLE
Deepcopy command during debugging leads to error message

### ISSUE THREAD

**Issue by VolkerSmits** [JuliaDebug/JuliaInterpreter.jl#294] opened 2019-05-27 11:37 UTC
Hello,

I got an error message during debugging when I step over a command, which makes a copy of an object of a mutable struct with the function deepcopy.

ERROR: MethodError: no method matching ccall_jl_set_nth_field_6c4adf90_7e15_11e9_17a8_a11fb0465f61(::Population.Pop, ::Int64, ::Int64)

The strange thing is: If I evaluate the expression for example in Jupyter or in the prompt, it will work. Does somebody have this issue, too?

I use pop_tmp = deepcopy(pop) to make the copy of the object.

Best regards,
Volker

**Comment by KristofferC** [comment] 2019-05-27 11:40
What is `pop`? Please provide a minimal example that reproduce the issue.

**Comment by VolkerSmits** [comment] 2019-05-27 11:45
Hi,

pop is an object of the following mutable struct

mutable struct Pop
	num_size
	num_parm_types
	num_obj_func
	obj_func_names
	par_names
	sorting_method
	dist_method
	obj_func_goal
	parms_lim
	par_size
	min_gap
	obj_func_goal_val
	individuals
	obj_func
end

The variable individuals is a list of another mutable struct and the variable obj_func is a DataFrame. All other variables are just lists, arrays or constants.

**Comment by timholy** [comment] 2019-05-27 20:47
Unless you're planning to submit a PR to fix it yourself, it's hard to do a lot with this because replicating user bugs is often much harder than it seems. Ideally we'd have an example we can just copy/paste and run ourselves without having to make guesses about what matters and what does not.

**Comment by VolkerSmits** [comment] 2019-05-28 06:26
Normally I would do so, but I´m working for a company on this project. This is the reason why I don´t post the whole code. I will try to make short example were all relevant things are included, so that you don´t have to guess.

**Comment by VolkerSmits** [comment] 2019-05-28 08:10
I tried to reconstruct the issue, but I can´t. Even in the orignal code it works now. I´m little bit confused why it works now, but I think you can discard this issue. Sorry that I spend your time

**Comment by KristofferC** [comment] 2019-05-28 08:19
For future reference, it would be good to post the versions of the packages used in case you maybe were on an old version of JuliaInterpreter.

Closing this now but feel free to comment if you can find a reproducer.

**Closed by KristofferC** 2019-05-28 08:19 UTC
Labels: bug

**Comment by VolkerSmits** [comment] 2019-05-28 08:43
Ok. I will keep this in mind. For the sake of completeness I use Julia v1.1, Atom 1.37.0 x64, Juno 0.8.3, Rebugger v0.3.2, Debugger v0.4.0, Revise v2.1.4 and JuliaInterpreter v0.5.1.
