### ISSUE TITLE
MethodError: no method matching getindex(::Core.Compiler.IRCode, ::typeof(Core.Compiler.getindex))

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#265] opened 2019-04-03 15:24 UTC
Not quite sure where the fault lies, but should report it somewhere:

```julia
julia> using JuliaInterpreter, Debugger, Zygote

julia> @enter (Zygote.Adjoint)((Zygote.code_ir)(Zygote.pow, (Zygote.typesof)(2, 3)), varargs=(Zygote.varargs)((InteractiveUtils.which)(Zygote.pow, (Base.typesof)(2, 3)), (Zygote.length)((Zygote.pow, 2, 3))))
In #Adjoint#68(varargs, , ir) at /home/tim/.julia/packages/Zygote/mlF4T/src/compiler/reverse.jl:440
>440  Adjoint(ir::IRCode; varargs = nothing) = Adjoint(Primal(ir, varargs = varargs))

About to run: (Core.apply_type)(NamedTuple, (:varargs,))
1|debug> c
ERROR: MethodError: no method matching getindex(::Core.Compiler.IRCode, ::typeof(Core.Compiler.getindex))
You may have intended to import Base.getindex
Closest candidates are:
  getindex(::Core.Compiler.IRCode, ::Core.SSAValue) at compiler/ssair/ir.jl:236
  getindex(::Core.Compiler.TypesView, ::Any) at compiler/ssair/ir.jl:713
  getindex(::Type{Any}, ::Any...) at array.jl:356
  ...
Stacktrace:
 [1] getindex(::Core.Compiler.IRCode, ::Tuple{Core.SSAValue}) at /home/tim/.julia/packages/IRTools/IHXm6/src/ir/wrap.jl:14
 [2] record_globals!(::Core.Compiler.IRCode) at /home/tim/.julia/packages/Zygote/mlF4T/src/compiler/reverse.jl:117
 [3] #Primal#42(::Nothing, ::DataType, ::Core.Compiler.IRCode) at /home/tim/.julia/packages/Zygote/mlF4T/src/compiler/reverse.jl:229
 [4] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:varargs,),Tuple{Nothing}}, ::DataType, ::Core.Compiler.IRCode) at none:0
 [5] #Adjoint#68(::Nothing, ::DataType, ::Core.Compiler.IRCode) at /home/tim/.julia/packages/Zygote/mlF4T/src/compiler/reverse.jl:440
 [6] (::getfield(Core, Symbol("#kw#Type")))(::NamedTuple{(:varargs,),Tuple{Nothing}}, ::DataType, ::Core.Compiler.IRCode) at none:0
```

Zygote is trouble :smile:.

**Comment by KristofferC** [comment] 2019-04-03 15:39
Moved here due to:

```
julia> @interpret (Zygote.Adjoint)((Zygote.code_ir)(Zygote.pow, (Zygote.typesof)(2, 3)), varargs=(Zygote.varargs)((InteractiveUtils.which)(Zygote.pow, (Base.typesof)(2, 3)), (Zygote.length)((Zygote.pow, 2, 3))))
ERROR: MethodError: no method matching getindex(::Core.Compiler.IRCode, ::typeof(Core.Compiler.getindex))
You may have intended to import Base.getindex
Closest candidates are:
  getindex(::Core.Compiler.IRCode, ::Core.SSAValue) at compiler/ssair/ir.jl:236
  getindex(::Core.Compiler.TypesView, ::Any) at compiler/ssair/ir.jl:713
  getindex(::Type{Any}, ::Any...) at array.jl:356
  ...
Stacktrace:
 [1] #prepare_call#14(::Bool, ::Function, ::Any, ::Array{Any,1}) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\construct.jl:228
 [2] #prepare_call at .\none:0 [inlined]
 [3] #get_call_framecode#32(::Bool, ::Function, ::Array{Any,1}, ::JuliaInterpreter.FrameCode, ::Int64) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\localmethtable.jl:53
 [4] #get_call_framecode at .\none:0 [inlined]
 [5] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:227
 [6] evaluate_call_recurse! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:205 [inlined]
 [7] eval_rhs(::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:371
 [8] step_expr!(::Any, ::Frame, ::Any, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:504
 [9] step_expr! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:543 [inlined]
 [10] finish!(::Any, ::Frame, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:14
 [11] finish_and_return! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:29 [inlined]
 [12] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:242
 [13] evaluate_call_recurse! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:205 [inlined]
 [14] eval_rhs(::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:371
 [15] step_expr!(::Any, ::Frame, ::Any, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:421
 [16] step_expr! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:543 [inlined]
 [17] finish!(::Any, ::Frame, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:14
 [18] finish_and_return! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:29 [inlined]
 [19] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:242
 [20] evaluate_call_recurse! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:205 [inlined]
 [21] eval_rhs(::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:371
 [22] step_expr!(::Any, ::Frame, ::Any, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:504
 [23] step_expr! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:543 [inlined]
 [24] finish!(::Any, ::Frame, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:14
 [25] finish_and_return! at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\commands.jl:29 [inlined]
```

**Comment by timholy** [comment] 2019-04-03 16:08
This comes from macroexpanding [this line](https://github.com/FluxML/Zygote.jl/blob/0f49c3f6bf6b603014c3f7de640b6a53f16f2448/src/precompile.jl#L15).

**Comment by KristofferC** [comment] 2019-04-03 16:11
I think this is just https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/257?

**Comment by KristofferC** [comment] 2019-04-03 16:14
On https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/258

```
julia>  @interpret (Zygote.Adjoint)((Zygote.code_ir)(Zygote.pow, (Zygote.typesof)(2, 3)), varargs=(Zygote.varargs)((InteractiveUtils.which)(Zygote.pow, (Base.typesof)(2, 3)), (Zygote.length)((Zygote.pow, 2, 3))))
ERROR: AssertionError: not implemented
Stacktrace:
 [1] maybe_evaluate_builtin(::Frame, ::Expr, ::Bool) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\builtins-julia1.1.jl:194
 [2] #evaluate_call_recurse!#37(::Bool, ::Function, ::Any, ::Frame, ::Expr) at C:\Users\Kristoffer\Debugging\JuliaInterpreter\src\interpret.jl:214
```

**Comment by timholy** [comment] 2019-04-03 16:14
I'm not so sure:
```julia
julia> Base.getindex === Core.Compiler.getindex
false
```

**Comment by KristofferC** [comment] 2019-04-03 16:16
Yes. The problem is that the SSAValue that should have been in `getindex(::Core.Compiler.IRCode, ::Core.SSAValue)` got replaced with something else, so it got called as ` getindex(::Core.Compiler.IRCode, ::typeof(Core.Compiler.getindex)`.

**Comment by KristofferC** [comment] 2019-04-07 12:31
Closing as dup of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/257.

**Closed by KristofferC** 2019-04-07 12:31 UTC
